config/routes.rb
Arbitrage::Application.routes.draw do

  devise_for :users do
    resources :games, only: [:index, :show, :new, :create]
  end

  root :to => 'welcome#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  attr_accessible :score
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :games
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

app/views/games/new.html.erb
<h2>Welcome <%= current_user.username%></h2>
<p class = "turns">Turns Remaining: 15</p>
<div class= "prices_monitor">
  <table class = "table">
      <thead>
        <th>Terminal</th>
        <th></th>
        <th></th>
      </thead>
    <tbody>
      <tr>
        <th>Commodity</th>
        <th>Price</th>
        <th>Buy</th>
      </tr>
    </tbody>
  </table>
</div>

<div class= "user_panel">
  <table class = "table">
    <thead>
      <tr class = "balance">
        <th>Balance</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th>Item</th>
        <th>Quantity</th>
        <th>Current Value</th>
        <th>Sell</th>
      </tr>
    </tbody>
  </table>
</div>

<button class= "btn btn-large btn-inverse next_day_btn" style="margin-top:20px">Next Day</button>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/layouts/_faq.html.erb
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">How to Play</h3>
  </div>
  <div class="modal-body">
    <h4>Goal</h4>
    <p>Your Goal is to make as much money as possible given by buying and selling goods in 15 days. After you are completed buying and selling goods, click "Next Day" to continue.</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <a class="brand" href="#">Arbitrage</a>
    <ul class="nav">
      <li class="active"><%= link_to "Home", root_path%></li>
      <li><a href="#">High Scores</a></li>
      <li><a href="#myModal" data-toggle="modal">FAQ</a></li>
    </ul>
    <ul class="nav pull-right">
      <%if current_user %>
        <li><a>Welcome <%=current_user.username%></a></li>
        <li><%=link_to "Sign Out", destroy_user_session_path, :method => :delete%></li>
      <%else%>
        <li><a href="#myModal_signIn" data-toggle="modal">Sign In</a></li>
        <li><%=link_to "Sign Up", new_user_registration_path%></li>
      <%end%>
    </ul>
  </div>
</div>

<!-- link_to "Sign In", new_user_session_path -->

app/views/layouts/_sign_in.html.erb
<!-- Modal -->
<div id="myModal_signIn" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Sign-In</h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>

</div>


<!-- <h4>Goal</h4>
    <p>Your Goal is to make as much money as possible given by buying and selling goods in 15 days. After you are completed buying and selling goods, click "Next Day" to continue.</p> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arbitrage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav'%>
  <%= render 'layouts/faq'%>
  <%= render 'layouts/sign_in'%>
  <div class = "container">
<!--   <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<div class = "welcome_page">
<h1>See If You Can Be The Best</h1>
  <% if current_user %>
    <%= link_to "Start Game", new_game_path, :class => "btn btn-large btn-danger welcome_page_btn"%>
  <%end%>
</div>